In [434]:
import numpy as np
from sklearn import svm
import pandas as pd
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn.model_selection import train_test_split # Import train_test_split function
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation
from sklearn.metrics import confusion_matrix
from sklearn.externals import joblib
from sklearn.svm import SVC,LinearSVC
from sklearn.multiclass import OneVsRestClassifier
from sklearn import metrics
from sklearn.model_selection import GridSearchCV
import time
from sklearn.metrics import accuracy_score
import sys
from sklearn.neighbors import KNeighborsClassifier
from sklearn import linear_model
import matplotlib.pyplot as plt
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense, Activation, Dropout
from keras.utils import np_utils
from sklearn import preprocessing,ensemble
from sklearn.feature_selection import VarianceThreshold
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.ensemble import GradientBoostingClassifier 
from sklearn.model_selection import GridSearchCV
from sklearn.decomposition import PCA
import lightgbm as lgb
from sklearn.naive_bayes import GaussianNB 
from xgboost import XGBClassifier
from sklearn.feature_selection import SelectPercentile, f_classif
from sklearn.linear_model import LinearRegression
import seaborn as sns
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold


In [435]:
def convert(x):
    ids = np.unique(x)
    vals = 0
    pd = np.zeros((x.shape))
    for item in ids:
        pd[x==item] = vals
    return pd

In [436]:
train = pd.read_csv("train.csv")
train.head()

ID  G1  G2  G3  G4  G5  T1  T2  T3  T4  T5  T6  T7  T8  T9  T10  T11  T12  \
0   1   0   1   0   1   0   1   0   0   0   0   0   0   0   0    0    0    0   
1   2   0   1   0   1   0   1   1   0   0   0   0   1   0   0    0    0    0   
2   3   1   1   0   1   1   1   0   0   0   0   0   0   0   0    0    0    0   
3   4   1   1   0   1   0   0   0   0   0   0   0   0   0   0    0    0    0   
4   5   0   0   1   1   0   0   0   0   0   0   0   0   0   0    0    0    0   

   T13  T14  T15  T16  T17  T18  T19  T20  T21  T22  T23  T24  T25  T26  T27  \
0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0   
1    1    0    0    0    0    0    0    0    0    0    0    0    0    0    0   
2    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0   
3    0    0    0    0    0    0    0    0    0    0    0    1    0    0    0   
4    0    0    0    0    0    1    0    0    0    0    0    0    0    0    0   

   T28  T29  T30  R1  R2  R3  R4  R5  R6  R7  O1  O2  O3  O4  Y  
0    0    0    0   0   0   0   0   0   1   0   0   0   1   0  1  
1    0    1    0   0   0   0   0   0   1   0   0   0   1   0  1  
2    0    0    0   0   0   1   0   0   0   0   0   0   0   1  1  
3    0    0    0   0   0   0   0   0   0   1   0   1   0   0  1  
4    0    0    0   0   0   0   0   0   1   0   0   1   0   0  1

In [437]:
train1 = pd.read_csv("train1.csv")
train1.head()

ID  G1  G2  G3  G4  G5  T1  T2  T3  T4  T5  T6  T7  T8  T9  T10  T11  T12  \
0   1   0   1   0   1   0   1   0   0   0   0   0   0   0   0    0    0    0   
1   2   0   1   0   1   0   1   1   0   0   0   0   1   0   0    0    0    0   
2   3   1   1   0   1   1   1   0   0   0   0   0   0   0   0    0    0    0   
3   4   1   1   0   1   0   0   0   0   0   0   0   0   0   0    0    0    0   
4   5   0   0   1   1   0   0   0   0   0   0   0   0   0   0    0    0    0   

   T13  T14  T15  T16  T17  T18  T19  T20  T21  T22  T23  T24  T25  T26  T27  \
0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0   
1    1    0    0    0    0    0    0    0    0    0    0    0    0    0    0   
2    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0   
3    0    0    0    0    0    0    0    0    0    0    0    1    0    0    0   
4    0    0    0    0    0    1    0    0    0    0    0    0    0    0    0   

   T28  T29  T30  R1  R2  R3  R4  R5  R6  R7  O1  O2  O3  O4  Y  
0    0    0    0   0   0   0   0   0   1   0   0   0   1   0  1  
1    0    1    0   0   0   0   0   0   1   0   0   0   1   0  1  
2    0    0    0   0   0   1   0   0   0   0   0   0   0   1  1  
3    0    0    0   0   0   0   0   0   0   1   0   1   0   0  1  
4    0    0    0   0   0   0   0   0   1   0   0   1   0   0  1

In [438]:
train2 = pd.read_csv("train2.csv")
train2.head()

ID  G1  G2  G3  G4  G5  T1  T2  T3  T4  T5  T6  T7  T8  T9  T10  T11  \
0  1733   1   1   0   0   0   0   0   0   0   0   0   0   0   0    0    0   
1  1734   0   1   0   1   1   0   0   0   0   0   0   0   0   0    0    0   
2  1735   0   1   0   0   1   0   0   0   0   0   0   0   0   0    0    0   
3  1736   1   1   0   0   0   0   0   0   0   0   0   0   0   0    0    0   
4  1737   1   1   0   0   0   0   0   0   0   0   0   0   0   0    0    0   

   T12  T13  T14  T15  T16  T17  T18  T19  T20  T21  T22  T23  T24  T25  T26  \
0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0   
1    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0   
2    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0   
3    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0   
4    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0   

   T27  T28  T29  T30  R1  R2  R3  R4  R5  R6  R7  O1  O2  O3  O4  Y  
0    0    0    0    1   0   0   0   0   0   0   1   0   0   0   1  2  
1    0    0    0    1   0   0   0   0   0   0   1   0   0   0   1  2  
2    0    0    0    1   0   0   0   0   0   1   0   0   0   0   1  2  
3    0    0    0    1   0   0   0   0   0   0   1   0   0   0   1  2  
4    0    0    0    1   0   0   0   0   0   1   0   0   0   0   1  2

In [439]:
train3 = pd.read_csv("train3.csv")
train3.head()

ID  G1  G2  G3  G4  G5  T1  T2  T3  T4  T5  T6  T7  T8  T9  T10  T11  \
0  1927   1   1   0   1   0   0   0   0   0   0   0   0   0   0    1    1   
1  1928   1   1   0   1   0   0   0   0   0   1   0   0   0   0    0    0   
2  1929   1   1   0   1   0   1   0   0   0   0   0   0   0   0    0    0   
3  1930   0   1   0   1   0   0   0   0   0   0   0   0   0   0    0    0   
4  1931   1   1   0   1   0   0   0   0   0   0   0   1   0   0    0    0   

   T12  T13  T14  T15  T16  T17  T18  T19  T20  T21  T22  T23  T24  T25  T26  \
0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0   
1    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0   
2    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0   
3    0    0    0    0    0    0    1    0    1    0    0    0    0    0    0   
4    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0   

   T27  T28  T29  T30  R1  R2  R3  R4  R5  R6  R7  O1  O2  O3  O4  Y  
0    0    0    0    0   0   0   0   0   0   1   0   0   0   1   0  3  
1    0    0    0    0   0   0   0   0   0   1   0   0   0   1   0  3  
2    0    0    0    0   0   0   0   0   0   0   1   0   1   0   0  3  
3    0    0    0    0   0   0   0   0   0   0   1   0   1   0   0  3  
4    0    0    0    0   0   0   0   0   0   1   0   0   1   0   0  3

In [440]:
X1 = train1.drop(['Y'], axis=1)
X1['ID'] = convert(X1['ID'].values)
X1 = X1.apply(pd.to_numeric,errors='coerce')
X1.fillna(0,inplace =True)
X1=X1.astype(float)
pd.options.display.max_columns = None
X1

ID   G1   G2   G3   G4   G5   T1   T2   T3   T4   T5   T6   T7   T8  \
0     0.0  0.0  1.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1     0.0  0.0  1.0  0.0  1.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0   
2     0.0  1.0  1.0  0.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
3     0.0  1.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
4     0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
1727  0.0  1.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1728  0.0  0.0  1.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0   
1729  0.0  1.0  1.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1730  0.0  0.0  1.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1731  0.0  1.0  1.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   

       T9  T10  T11  T12  T13  T14  T15  T16  T17  T18  T19  T20  T21  T22  \
0     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1     0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
2     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
3     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
4     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
1727  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1728  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1729  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1730  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1731  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

      T23  T24  T25  T26  T27  T28  T29  T30   R1   R2   R3   R4   R5   R6  \
0     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0   
1     0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0   
2     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0   
3     0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
4     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
1727  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1728  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1729  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0   
1730  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1731  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

       R7   O1   O2   O3   O4  
0     0.0  0.0  0.0  1.0  0.0  
1     0.0  0.0  0.0  1.0  0.0  
2     0.0  0.0  0.0  0.0  1.0  
3     1.0  0.0  1.0  0.0  0.0  
4     0.0  0.0  1.0  0.0  0.0  
...   ...  ...  ...  ...  ...  
1727  1.0  0.0  1.0  0.0  0.0  
1728  1.0  0.0  1.0  0.0  0.0  
1729  0.0  0.0  0.0  0.0  1.0  
1730  1.0  0.0  1.0  0.0  0.0  
1731  1.0  0.0  1.0  0.0  0.0  

[1732 rows x 47 columns]

In [441]:
X2 = train2.drop(['Y'], axis=1)
X2['ID'] = convert(X2['ID'].values)
X2 = X2.apply(pd.to_numeric,errors='coerce')
X2.fillna(0,inplace =True)
X2=X2.astype(float)
pd.options.display.max_columns = None
X2

ID   G1   G2   G3   G4   G5   T1   T2   T3   T4   T5   T6   T7   T8  \
0    0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1    0.0  0.0  1.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
2    0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
3    0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
4    0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
189  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
190  0.0  1.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
191  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
192  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
193  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

      T9  T10  T11  T12  T13  T14  T15  T16  T17  T18  T19  T20  T21  T22  \
0    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
2    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
3    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
4    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
189  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
190  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
191  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
192  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
193  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

     T23  T24  T25  T26  T27  T28  T29  T30   R1   R2   R3   R4   R5   R6  \
0    0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0   
1    0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0   
2    0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0   
3    0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0   
4    0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
189  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0   
190  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0   
191  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0   
192  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0   
193  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  1.0  0.0   

      R7   O1   O2   O3   O4  
0    1.0  0.0  0.0  0.0  1.0  
1    1.0  0.0  0.0  0.0  1.0  
2    0.0  0.0  0.0  0.0  1.0  
3    1.0  0.0  0.0  0.0  1.0  
4    0.0  0.0  0.0  0.0  1.0  
..   ...  ...  ...  ...  ...  
189  1.0  0.0  0.0  0.0  1.0  
190  0.0  0.0  0.0  0.0  1.0  
191  0.0  0.0  0.0  0.0  1.0  
192  1.0  0.0  0.0  0.0  1.0  
193  1.0  0.0  0.0  0.0  1.0  

[194 rows x 47 columns]

In [442]:
X3 = train3.drop(['Y'], axis=1)
X3['ID'] = convert(X3['ID'].values)
X3 = X3.apply(pd.to_numeric,errors='coerce')
X3.fillna(0,inplace =True)
X3=X3.astype(float)
pd.options.display.max_columns = None
X3

ID   G1   G2   G3   G4   G5   T1   T2   T3   T4   T5   T6   T7   T8  \
0    0.0  1.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1    0.0  1.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0   
2    0.0  1.0  1.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
3    0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
4    0.0  1.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
948  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
949  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
950  0.0  1.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
951  0.0  1.0  1.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   
952  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   

      T9  T10  T11  T12  T13  T14  T15  T16  T17  T18  T19  T20  T21  T22  \
0    0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
2    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
3    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0   
4    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
948  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
949  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
950  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
951  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
952  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

     T23  T24  T25  T26  T27  T28  T29  T30   R1   R2   R3   R4   R5   R6  \
0    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0   
1    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0   
2    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
3    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
4    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
948  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
949  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0   
950  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0   
951  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0   
952  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0   

      R7   O1   O2   O3   O4  
0    0.0  0.0  0.0  1.0  0.0  
1    0.0  0.0  0.0  1.0  0.0  
2    1.0  0.0  1.0  0.0  0.0  
3    1.0  0.0  1.0  0.0  0.0  
4    0.0  0.0  1.0  0.0  0.0  
..   ...  ...  ...  ...  ...  
948  1.0  0.0  1.0  0.0  0.0  
949  0.0  0.0  0.0  0.0  1.0  
950  0.0  0.0  1.0  0.0  0.0  
951  0.0  1.0  0.0  1.0  0.0  
952  1.0  0.0  1.0  0.0  0.0  

[953 rows x 47 columns]

In [443]:
y1=train1['Y']
y2=train2['Y']
y3=train3['Y']
y1,y2,y3

(0       1
 1       1
 2       1
 3       1
 4       1
        ..
 1727    1
 1728    1
 1729    1
 1730    1
 1731    1
 Name: Y, Length: 1732, dtype: int64, 0      2
 1      2
 2      2
 3      2
 4      2
       ..
 189    2
 190    2
 191    2
 192    2
 193    2
 Name: Y, Length: 194, dtype: int64, 0      3
 1      3
 2      3
 3      3
 4      3
       ..
 948    3
 949    3
 950    3
 951    3
 952    3
 Name: Y, Length: 953, dtype: int64)

In [444]:
X = train.drop(['Y'], axis=1)
X['ID'] = convert(X['ID'].values)
X = X.apply(pd.to_numeric,errors='coerce')
X.fillna(0,inplace =True)
X=X.astype(float)
pd.options.display.max_columns = None
X

ID   G1   G2   G3   G4   G5   T1   T2   T3   T4   T5   T6   T7   T8  \
0     0.0  0.0  1.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1     0.0  0.0  1.0  0.0  1.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0   
2     0.0  1.0  1.0  0.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
3     0.0  1.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
4     0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
3528  0.0  0.0  1.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
3529  0.0  0.0  1.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
3530  0.0  1.0  1.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
3531  0.0  1.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0   
3532  0.0  0.0  1.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

       T9  T10  T11  T12  T13  T14  T15  T16  T17  T18  T19  T20  T21  T22  \
0     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1     0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
2     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
3     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
4     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
3528  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
3529  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0   
3530  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
3531  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
3532  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

      T23  T24  T25  T26  T27  T28  T29  T30   R1   R2   R3   R4   R5   R6  \
0     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0   
1     0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0   
2     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0   
3     0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
4     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
3528  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
3529  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0   
3530  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
3531  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0   
3532  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   

       R7   O1   O2   O3   O4  
0     0.0  0.0  0.0  1.0  0.0  
1     0.0  0.0  0.0  1.0  0.0  
2     0.0  0.0  0.0  0.0  1.0  
3     1.0  0.0  1.0  0.0  0.0  
4     0.0  0.0  1.0  0.0  0.0  
...   ...  ...  ...  ...  ...  
3528  1.0  0.0  1.0  0.0  0.0  
3529  0.0  0.0  0.0  1.0  0.0  
3530  1.0  0.0  1.0  0.0  0.0  
3531  0.0  0.0  0.0  1.0  0.0  
3532  1.0  0.0  0.0  0.0  1.0  

[3533 rows x 47 columns]

In [445]:
y=train['Y']
y

0       1
1       1
2       1
3       1
4       1
       ..
3528    3
3529    3
3530    3
3531    3
3532    3
Name: Y, Length: 3533, dtype: int64

In [446]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [447]:
clf = GradientBoostingClassifier(loss="deviance",learning_rate=0.1,n_estimators=225,max_features=46,min_samples_split=75,min_samples_leaf=1,random_state=0)
clf.fit(X_train, y_train)
test_predict=clf.predict(X_test)

In [448]:
#kfold = KFold(n_splits=5)
#cross_val_score(clf, X_train, y_train, cv=kfold)

In [449]:
test_predict1=clf.predict(X1)
test_predict2=clf.predict(X2)
test_predict3=clf.predict(X3)

In [450]:
test_predict1

array([1, 1, 3, ..., 1, 3, 3], dtype=int64)

In [451]:
test_predict2

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 3, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [452]:
test_predict3

array([3, 3, 3, 3, 3, 1, 3, 1, 3, 3, 3, 1, 3, 3, 3, 3, 3, 3, 3, 1, 3, 1,
       1, 3, 3, 3, 1, 1, 3, 3, 3, 3, 1, 3, 3, 3, 1, 3, 1, 3, 3, 1, 3, 3,
       3, 3, 3, 1, 1, 3, 1, 3, 1, 3, 3, 3, 3, 1, 3, 1, 1, 3, 1, 1, 3, 3,
       1, 3, 3, 1, 3, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 3, 3, 3, 3, 3, 3, 3,
       3, 1, 3, 3, 3, 3, 3, 3, 1, 3, 3, 3, 3, 1, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 1, 3, 3, 3, 3, 1, 3, 3, 3, 1, 3, 1, 1, 1, 3, 3, 3, 1, 3, 3, 3,
       3, 3, 1, 3, 3, 1, 3, 3, 3, 3, 3, 3, 3, 1, 3, 1, 3, 3, 3, 1, 1, 3,
       3, 3, 3, 3, 3, 3, 1, 1, 3, 1, 3, 3, 3, 3, 3, 3, 3, 1, 3, 1, 1, 3,
       3, 3, 1, 1, 3, 3, 3, 3, 3, 3, 3, 3, 1, 1, 3, 1, 1, 3, 1, 1, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 3, 3, 3, 3, 3, 1,
       3, 1, 3, 3, 3, 3, 1, 3, 3, 1, 3, 3, 1, 3, 1, 3, 3, 3, 1, 3, 3, 3,
       1, 3, 3, 1, 3, 3, 3, 1, 3, 3, 1, 3, 3, 3, 3, 3, 3, 3, 3, 1, 3, 1,
       3, 3, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 1, 3,

In [453]:
score1 = accuracy_score(y1, test_predict1)
score2 = accuracy_score(y2, test_predict2)
score3 = accuracy_score(y3, test_predict3)
score1,score2,score3

(0.4792147806004619, 0.9536082474226805, 0.7628541448058762)

In [454]:
score = accuracy_score(y_test, test_predict)
score

0.5954738330975955

In [455]:
test_predict

array([1, 3, 3, 3, 3, 1, 1, 1, 2, 3, 3, 1, 1, 1, 1, 3, 3, 1, 3, 3, 1, 3,
       1, 3, 3, 3, 3, 3, 1, 3, 1, 3, 3, 3, 3, 3, 1, 3, 3, 3, 3, 3, 3, 1,
       1, 3, 1, 1, 3, 3, 1, 3, 3, 2, 3, 3, 3, 1, 3, 1, 3, 1, 3, 1, 1, 2,
       1, 1, 3, 3, 3, 1, 1, 3, 1, 1, 3, 3, 3, 1, 1, 3, 1, 1, 3, 3, 3, 1,
       1, 3, 1, 1, 1, 1, 3, 1, 1, 3, 1, 1, 1, 3, 3, 1, 1, 3, 3, 1, 3, 3,
       3, 3, 3, 1, 1, 3, 1, 3, 1, 3, 3, 1, 3, 3, 1, 3, 3, 3, 3, 3, 3, 1,
       3, 3, 1, 3, 1, 1, 1, 1, 3, 1, 3, 1, 3, 3, 1, 3, 2, 1, 1, 1, 1, 3,
       3, 1, 1, 3, 3, 1, 3, 2, 2, 1, 3, 1, 3, 1, 1, 3, 3, 3, 3, 3, 2, 3,
       3, 3, 3, 3, 3, 3, 1, 1, 3, 3, 3, 1, 1, 1, 3, 3, 3, 3, 3, 3, 3, 1,
       3, 3, 3, 3, 1, 3, 3, 3, 1, 2, 3, 3, 3, 3, 3, 1, 1, 2, 3, 3, 3, 1,
       3, 3, 1, 3, 3, 1, 3, 1, 3, 3, 1, 3, 3, 3, 2, 3, 1, 3, 1, 1, 3, 3,
       3, 3, 3, 3, 3, 3, 1, 1, 1, 1, 3, 1, 1, 3, 2, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 1, 3, 3, 3, 3, 1, 1, 3, 3, 3, 1, 3, 3, 1, 3, 2, 1, 3, 3,
       1, 3, 3, 3, 3, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3,

In [456]:
from sklearn.metrics import classification_report, confusion_matrix
print("Accuracy:",metrics.accuracy_score(y_test, test_predict))
print(confusion_matrix(y_test, test_predict))
print(classification_report(y_test, test_predict))

Accuracy: 0.5954738330975955
[[154   0 203]
 [  0  27   2]
 [ 80   1 240]]
              precision    recall  f1-score   support

           1       0.66      0.43      0.52       357
           2       0.96      0.93      0.95        29
           3       0.54      0.75      0.63       321

    accuracy                           0.60       707
   macro avg       0.72      0.70      0.70       707
weighted avg       0.62      0.60      0.59       707



In [457]:
test = pd.read_csv("test.csv")
test

ID  G1  G2  G3  G4  G5  T1  T2  T3  T4  T5  T6  T7  T8  T9  T10  T11  \
0      1   0   1   0   1   0   0   0   0   0   0   0   0   0   0    0    0   
1      2   1   1   0   0   0   0   0   0   0   0   0   0   0   0    0    0   
2      3   1   1   0   1   0   0   0   0   0   1   0   0   0   0    0    0   
3      4   1   1   0   1   0   0   0   0   0   0   0   0   0   0    0    0   
4      5   1   0   1   1   1   0   0   0   0   0   0   0   0   0    0    0   
..   ...  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ...   
295  296   1   1   0   0   0   0   0   0   0   0   0   0   0   0    0    1   
296  297   1   1   0   1   0   0   0   0   0   0   0   0   0   0    0    0   
297  298   0   1   0   1   0   1   0   0   0   0   0   0   0   0    0    0   
298  299   0   1   0   1   1   0   0   0   0   0   0   0   0   0    0    0   
299  300   1   1   0   1   0   0   0   0   0   0   0   0   0   0    0    1   

     T12  T13  T14  T15  T16  T17  T18  T19  T20  T21  T22  T23  T24  T25  \
0      0    0    0    0    0    0    0    0    0    0    0    0    1    0   
1      0    0    0    0    0    0    0    0    0    0    0    0    0    0   
2      0    0    0    0    0    0    0    0    0    0    0    0    0    0   
3      0    0    0    0    0    0    0    0    0    0    0    0    1    0   
4      0    0    0    0    0    0    0    0    0    0    0    0    0    0   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
295    0    0    0    0    0    0    0    0    0    0    0    0    0    0   
296    0    0    0    0    0    0    0    0    0    0    0    0    0    0   
297    0    0    0    0    0    0    0    0    0    0    0    0    0    0   
298    0    0    0    0    0    0    0    0    0    0    0    0    0    0   
299    0    0    0    0    0    0    0    0    0    0    0    0    0    0   

     T26  T27  T28  T29  T30  R1  R2  R3  R4  R5  R6  R7  O1  O2  O3  O4  
0      0    0    0    0    0   1   0   0   0   0   0   0   1   0   1   0  
1      0    0    0    0    1   0   0   0   0   0   0   1   0   0   0   1  
2      0    0    0    0    0   0   0   0   0   0   1   0   0   0   1   0  
3      0    0    0    0    0   0   0   0   0   0   0   1   0   1   0   0  
4      0    0    0    0    1   0   0   0   0   0   0   1   0   0   0   1  
..   ...  ...  ...  ...  ...  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  
295    0    0    0    0    0   0   0   0   0   0   1   0   0   0   0   1  
296    0    0    0    0    1   0   0   0   0   0   0   0   0   0   0   1  
297    0    0    0    0    0   0   0   0   0   0   0   1   0   0   0   1  
298    0    0    0    0    1   0   0   0   0   0   1   0   0   0   0   1  
299    0    0    0    0    0   0   0   0   0   0   1   0   0   0   1   0  

[300 rows x 47 columns]

In [458]:
test['ID'] = convert(test['ID'].values)
test = test.apply(pd.to_numeric,errors='coerce')
test.fillna(0,inplace =True)
test=test.astype(float)
pd.options.display.max_columns = None

In [459]:
test

ID   G1   G2   G3   G4   G5   T1   T2   T3   T4   T5   T6   T7   T8  \
0    0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1    0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
2    0.0  1.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0   
3    0.0  1.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
4    0.0  1.0  0.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
295  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
296  0.0  1.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
297  0.0  0.0  1.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
298  0.0  0.0  1.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
299  0.0  1.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

      T9  T10  T11  T12  T13  T14  T15  T16  T17  T18  T19  T20  T21  T22  \
0    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
2    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
3    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
4    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
295  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
296  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
297  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
298  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
299  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

     T23  T24  T25  T26  T27  T28  T29  T30   R1   R2   R3   R4   R5   R6  \
0    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0   
1    0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0   
2    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0   
3    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
4    0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
295  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0   
296  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0   
297  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
298  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0   
299  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0   

      R7   O1   O2   O3   O4  
0    0.0  1.0  0.0  1.0  0.0  
1    1.0  0.0  0.0  0.0  1.0  
2    0.0  0.0  0.0  1.0  0.0  
3    1.0  0.0  1.0  0.0  0.0  
4    1.0  0.0  0.0  0.0  1.0  
..   ...  ...  ...  ...  ...  
295  0.0  0.0  0.0  0.0  1.0  
296  0.0  0.0  0.0  0.0  1.0  
297  1.0  0.0  0.0  0.0  1.0  
298  0.0  0.0  0.0  0.0  1.0  
299  0.0  0.0  0.0  1.0  0.0  

[300 rows x 47 columns]

In [460]:
#test = test.drop(['T17','T6','T16','T22','T27','T28','T25','T23','T20','T26'], axis=1)

In [461]:
prediction = clf.predict(test)
prediction

array([3, 2, 3, 1, 2, 3, 2, 2, 1, 1, 3, 1, 2, 3, 2, 1, 1, 2, 3, 3, 2, 1,
       2, 2, 1, 2, 2, 2, 2, 2, 3, 2, 1, 1, 3, 2, 3, 3, 2, 2, 3, 3, 2, 2,
       3, 3, 3, 3, 2, 3, 3, 2, 1, 1, 2, 3, 3, 2, 1, 3, 2, 1, 3, 3, 3, 2,
       2, 3, 3, 1, 3, 2, 2, 2, 1, 3, 2, 2, 1, 3, 2, 3, 3, 3, 2, 3, 3, 1,
       3, 3, 2, 1, 1, 2, 3, 2, 2, 1, 1, 3, 2, 2, 2, 2, 1, 3, 1, 3, 3, 2,
       1, 1, 3, 2, 3, 3, 1, 3, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 2,
       2, 2, 2, 3, 2, 1, 3, 2, 3, 3, 1, 3, 3, 3, 2, 1, 2, 3, 2, 1, 1, 1,
       3, 1, 3, 1, 2, 2, 2, 2, 3, 3, 1, 1, 2, 2, 3, 2, 1, 1, 2, 2, 1, 1,
       3, 1, 2, 3, 2, 3, 3, 3, 1, 2, 3, 1, 1, 2, 2, 2, 1, 3, 3, 2, 1, 2,
       3, 1, 3, 2, 2, 3, 2, 3, 2, 1, 3, 3, 1, 2, 3, 3, 1, 3, 2, 3, 2, 2,
       3, 3, 2, 1, 3, 2, 3, 2, 3, 3, 3, 2, 3, 3, 3, 3, 3, 1, 1, 3, 1, 3,
       2, 3, 3, 2, 1, 3, 1, 3, 2, 3, 1, 3, 3, 3, 2, 1, 2, 2, 3, 3, 1, 3,
       1, 3, 1, 2, 3, 1, 1, 1, 3, 1, 3, 2, 3, 3, 3, 2, 2, 2, 3, 1, 1, 3,
       3, 3, 1, 1, 3, 2, 2, 1, 1, 1, 3, 1, 2, 3], d

In [462]:
clf.predict_proba(test)

array([[3.55927566e-01, 7.70568199e-06, 6.44064728e-01],
       [2.49771018e-03, 9.94472416e-01, 3.02987334e-03],
       [4.60330258e-01, 3.69935624e-06, 5.39666043e-01],
       [6.86898820e-01, 3.55839174e-06, 3.13097622e-01],
       [2.93090636e-03, 9.92585528e-01, 4.48356528e-03],
       [4.53272561e-01, 4.05467356e-06, 5.46723385e-01],
       [2.71167082e-03, 9.94893110e-01, 2.39521904e-03],
       [2.49771018e-03, 9.94472416e-01, 3.02987334e-03],
       [6.48672713e-01, 8.26286202e-05, 3.51244658e-01],
       [5.96883812e-01, 1.18755326e-03, 4.01928635e-01],
       [3.35390387e-01, 3.87415389e-06, 6.64605738e-01],
       [5.70868585e-01, 4.21010411e-06, 4.29127205e-01],
       [1.55540718e-04, 9.99703600e-01, 1.40858866e-04],
       [4.74381844e-01, 4.13901015e-06, 5.25614017e-01],
       [6.47980736e-02, 8.72258040e-01, 6.29438862e-02],
       [5.50185951e-01, 4.67213308e-06, 4.49809377e-01],
       [6.46177920e-01, 2.74995464e-05, 3.53794580e-01],
       [6.47980736e-02, 8.72258

In [463]:
results = np.around(clf.predict_proba(test),2)

In [464]:
results.transpose()

array([[0.36, 0.  , 0.46, 0.69, 0.  , 0.45, 0.  , 0.  , 0.65, 0.6 , 0.34,
        0.57, 0.  , 0.47, 0.06, 0.55, 0.65, 0.06, 0.41, 0.48, 0.  , 0.93,
        0.09, 0.  , 0.54, 0.  , 0.  , 0.  , 0.  , 0.  , 0.3 , 0.  , 0.57,
        0.5 , 0.48, 0.01, 0.48, 0.49, 0.01, 0.  , 0.48, 0.03, 0.  , 0.  ,
        0.48, 0.36, 0.45, 0.49, 0.  , 0.47, 0.48, 0.01, 0.98, 0.99, 0.  ,
        0.49, 0.49, 0.01, 0.69, 0.44, 0.  , 0.6 , 0.4 , 0.38, 0.44, 0.  ,
        0.  , 0.44, 0.45, 0.93, 0.36, 0.  , 0.02, 0.  , 0.5 , 0.48, 0.  ,
        0.  , 0.57, 0.43, 0.  , 0.42, 0.48, 0.17, 0.02, 0.42, 0.48, 0.86,
        0.39, 0.48, 0.  , 0.52, 0.57, 0.  , 0.44, 0.  , 0.01, 0.57, 0.68,
        0.48, 0.  , 0.  , 0.  , 0.  , 0.75, 0.48, 0.51, 0.48, 0.46, 0.14,
        0.66, 0.54, 0.49, 0.  , 0.03, 0.47, 0.5 , 0.45, 0.47, 0.  , 0.48,
        0.47, 0.49, 0.38, 0.49, 0.02, 0.49, 0.41, 0.49, 0.  , 0.31, 0.  ,
        0.  , 0.  , 0.  , 0.45, 0.  , 0.74, 0.44, 0.14, 0.37, 0.48, 0.68,
        0.48, 0.48, 0.48, 0.  , 0.57, 

In [465]:
submission=pd.read_csv("submit_samples.csv")

In [466]:
res = pd.DataFrame(results ,columns = ['C1','C2','C3'])
res

C1    C2    C3
0    0.36  0.00  0.64
1    0.00  0.99  0.00
2    0.46  0.00  0.54
3    0.69  0.00  0.31
4    0.00  0.99  0.00
..    ...   ...   ...
295  0.60  0.00  0.40
296  0.47  0.03  0.49
297  0.69  0.00  0.31
298  0.01  0.98  0.01
299  0.49  0.00  0.51

[300 rows x 3 columns]

In [467]:
res['ID'] = submission['ID']

In [468]:
colind = ['ID','C1','C2','C3']
res = res.reindex(columns=colind)
res

ID    C1    C2    C3
0      1  0.36  0.00  0.64
1      2  0.00  0.99  0.00
2      3  0.46  0.00  0.54
3      4  0.69  0.00  0.31
4      5  0.00  0.99  0.00
..   ...   ...   ...   ...
295  296  0.60  0.00  0.40
296  297  0.47  0.03  0.49
297  298  0.69  0.00  0.31
298  299  0.01  0.98  0.01
299  300  0.49  0.00  0.51

[300 rows x 4 columns]

In [469]:
res.to_csv('results9.csv',index=False)